apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        hazem-internship/angular: true
        hazem-internship/jx3-kubernetes-onprem: true
        hazem-internship/postegres: true
        hazem-internship/springboot-jenkins-multibranch-pipeline: true
        hazem-internship/vv: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        hazem-internship/angular: merge
        hazem-internship/jx3-kubernetes-onprem: merge
        hazem-internship/postegres: merge
        hazem-internship/springboot-jenkins-multibranch-pipeline: merge
        hazem-internship/vv: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - hazem-internship/jx3-kubernetes-onprem
        - hazem-internship/angular
        - hazem-internship/postegres
        - hazem-internship/springboot-jenkins-multibranch-pipeline
        - hazem-internship/vv
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - hazem-internship/jx3-kubernetes-onprem
        - hazem-internship/angular
        - hazem-internship/postegres
        - hazem-internship/springboot-jenkins-multibranch-pipeline
        - hazem-internship/vv
      target_url: http://lighthouse-jx.10.0.0.100.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
